fix/improvement: alpine redis & alpine mysql/mariadb

diff --git a/alpine/alpine-3.5-mysql-10.1/content/bin/entrypoint b/alpine/alpine-3.5-mysql-10.1/content/bin/entrypoint
--- a/alpine/alpine-3.5-mysql-10.1/content/bin/entrypoint
+++ b/alpine/alpine-3.5-mysql-10.1/content/bin/entrypoint
@@ -26,7 +26,8 @@ fi
 
 
 # Prepare MySQL configuration
-IS_NUMBER='^[0-9]+$'
+IS_STRING='^[a-zA-Z0-9_]+$'
+IS_PASSWORD='^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$'
 # ------------------------------------------------
 # MySQL credentials variable configuration
 MYSQL_USERNAME=${MYSQL_USERNAME:-}
@@ -35,12 +36,200 @@ MYSQL_DATABASE=${MYSQL_DATABASE:-}
 MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}
 # ------------------------------------------------
 # MySQL extra variable configuration
-
+MYSQL_FT_MIN_WORD_LEN=${MYSQL_FT_MIN_WORD_LEN:-4}
+MYSQL_FT_MAX_WORD_LEN=${MYSQL_FT_MAX_WORD_LEN:-20}
+MYSQL_TABLE_OPEN_CACHE=${MYSQL_TABLE_OPEN_CACHE:-400}
+MYSQL_KEY_BUFFER_SIZE=${MYSQL_KEY_BUFFER_SIZE:-32M}
+MYSQL_SORT_BUFFER_SIZE=${MYSQL_SORT_BUFFER_SIZE:-512K}
+MYSQL_READ_BUFFER_SIZE=${MYSQL_READ_BUFFER_SIZE:-8M}
+MYSQL_WRITE_BUFFER_SIZE=${MYSQL_WRITE_BUFFER_SIZE:-8M}
+MYSQL_READ_RND_BUFFER_SIZE=${MYSQL_READ_RND_BUFFER_SIZE:-512k}
+MYSQL_MAX_ALLOWED_PACKET=${MYSQL_MAX_ALLOWED_PACKET:-200M}
+MYSQL_NET_BUFFER_LENGTH=${MYSQL_NET_BUFFER_LENGTH:-8k}
+MYSQL_MYISAM_SORT_BUFFER_SIZE=${MYSQL_MYISAM_SORT_BUFFER_SIZE:-8M}
+MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-8M}
+MYSQL_INNODB_LOG_BUFFER_SIZE=${MYSQL_INNODB_LOG_BUFFER_SIZE:-8M}
+MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-32M}
+MYSQL_INNODB_USE_NATIVE_AIO=${MYSQL_INNODB_USE_NATIVE_AIO:-1}
+# ------------------------------------------------
+# MySQL replication variable configuration
+MYSQL_REPLICATION=${MYSQL_REPLICATION:-}
+MYSQL_REPLICATION_SERVER_ID_DEFAULT=$(sha256sum <<< $(hostname -i))
+MYSQL_REPLICATION_SERVER_ID_DEFAULT=${MYSQL_REPLICATION_SERVER_ID_DEFAULT:0:14}
+MYSQL_REPLICATION_SERVER_ID_DEFAULT=$((0x${MYSQL_REPLICATION_SERVER_ID_DEFAULT}%4294967295))
+MYSQL_REPLICATION_SERVER_ID=${MYSQL_REPLICATION_SERVER_ID:-MYSQL_REPLICATION_SERVER_ID_DEFAULT}
+MYSQL_REPLICATION_MASTER_HOST=${MYSQL_REPLICATION_MASTER_HOST:-}
+MYSQL_REPLICATION_MASTER_PORT=${MYSQL_REPLICATION_MASTER_PORT:-}
+MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-}
+MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-}
 # ------------------------------------------------
 # Write MySQL variable to configuration file
 { \
-
+  echo "[client]"; \
+  echo "port=3306"; \
+  echo "socket=/run/mysqld/mysqld.sock"; \
+  echo ""; \
+  echo ""; \
+  echo "[mysql]"; \
+  echo "no-auto-rehash"; \
+  echo ""; \
+  echo ""; \
+  echo "[mysqld]"; \
+  echo "port=3306"; \
+  echo "socket=/run/mysqld/mysqld.sock"; \
+  echo ""; \
+  echo "datadir=/data/mysql"; \
+  echo "ignore-db-dirs=lost+found"; \
+  echo ""; \
+  echo "skip-external-locking"; \
+  echo "skip_name_resolve"; \
+  echo ""; \
+  echo "lower_case_table_names=0"; \
+  echo "symbolic-links=0"; \
+  echo "sql_mode=''"; \
+  echo ""; \
+  echo "ft_min_word_len=${MYSQL_FT_MIN_WORD_LEN}"; \
+  echo "ft_max_word_len=${MYSQL_FT_MAX_WORD_LEN}"; \
+  echo ""; \
+  echo "table_open_cache=${MYSQL_TABLE_OPEN_CACHE}"; \
+  echo "key_buffer_size=${MYSQL_KEY_BUFFER_SIZE}"; \
+  echo "sort_buffer_size=${MYSQL_SORT_BUFFER_SIZE}"; \
+  echo "read_buffer_size=${MYSQL_READ_BUFFER_SIZE}"; \
+  echo "read_rnd_buffer_size=${MYSQL_READ_RND_BUFFER_SIZE}"; \
+  echo "max_allowed_packet=${MYSQL_MAX_ALLOWED_PACKET}"; \
+  echo "net_buffer_length=${MYSQL_NET_BUFFER_LENGTH}"; \
+  echo "thread_stack=256K"; \
+  echo ""; \
+  echo "myisam_sort_buffer_size=${MYSQL_MYISAM_SORT_BUFFER_SIZE}"; \
+  echo ""; \
+  echo "innodb_log_file_size=${MYSQL_INNODB_LOG_FILE_SIZE}"; \
+  echo "innodb_log_buffer_size=${MYSQL_INNODB_LOG_BUFFER_SIZE}"; \
+  echo "innodb_buffer_pool_size=${MYSQL_INNODB_BUFFER_POOL_SIZE}"; \
+  echo "innodb_use_native_aio=${MYSQL_INNODB_USE_NATIVE_AIO}"; \
+  echo ""; \
+  echo "# Replication"; \
+  echo "log-bin=mysql-bin"; \
+  echo "binlog_format=mixed"; \
+  echo ""; \
+  if [[ $MYSQL_REPLICATION == "slave" ]]; \
+  then
+    echo "server-id=${MYSQL_REPLICATION_SERVER_ID}"; \  
+    echo "master-host=${MYSQL_REPLICATION_MASTER_HOST}"; \
+    echo "master-port=${MYSQL_REPLICATION_MASTER_PORT}"; \
+    echo "master-user=${MYSQL_REPLICATION_USER}"; \
+    echo "master-password=${MYSQL_REPLICATION_PASSWORD}"; \
+  else
+    echo "server-id=1"; \
+  fi; \
+  echo ""; \
+  echo ""; \
+  echo "[myisamchk]"; \
+  echo "ft_min_word_len=${MYSQL_FT_MIN_WORD_LEN}"; \
+  echo "ft_max_word_len=${MYSQL_FT_MAX_WORD_LEN}"; \
+  echo ""; \
+  echo "key_buffer_size=${MYSQL_KEY_BUFFER_SIZE}"; \
+  echo "sort_buffer_size=${MYSQL_SORT_BUFFER_SIZE}"; \
+  echo "read_buffer=${MYSQL_READ_BUFFER_SIZE}"; \
+  echo "write_buffer=${MYSQL_WRITE_BUFFER_SIZE}"; \
+  echo ""; \
+  echo ""; \
+  echo "[mysqldump]"; \
+  echo "quick"; \
+  echo "max_allowed_packet=${MYSQL_MAX_ALLOWED_PACKET}"; \
+  echo ""; \
+  echo ""; \
+  echo "[mysqlhotcopy]"; \
+  echo "interactive-timeout"; \
 } > /etc/mysql/my.cnf
+# ------------------------------------------------
+# Validate MySQL credentials variable configuration
+if [[ ! -z $MYSQL_USERNAME ]]; then
+  if ! [[ $MYSQL_USERNAME =~ $IS_STRING ]]; then
+    echo "Failed to configure MYSQL_USERNAME variable. Fallback to default MYSQL_USERNAME value as admin"
+    MYSQL_USERNAME="admin"
+  else
+    if [[ ${#MYSQL_USERNAME} -gt 32 ]]; then
+      echo "Failed to configure MYSQL_USERNAME variable. Fallback to default MYSQL_USERNAME value as admin"
+      MYSQL_USERNAME="admin"
+    fi
+  fi
+else
+  echo "Failed to configure MYSQL_USERNAME variable. Fallback to default MYSQL_USERNAME value as admin"
+  MYSQL_USERNAME="admin"
+fi
+if [[ ! -z $MYSQL_PASSWORD ]]; then
+  if ! [[ $MYSQL_PASSWORD =~ $IS_PASSWORD ]]; then
+    echo "Failed to configure MYSQL_PASSWORD variable. Fallback to default MYSQL_PASSWORD value as password"
+    MYSQL_PASSWORD="password"
+  fi
+else
+  echo "Failed to configure MYSQL_PASSWORD variable. Fallback to default MYSQL_PASSWORD value as password"
+  MYSQL_PASSWORD="password"
+fi
+if [[ ! -z $MYSQL_DATABASE ]]; then
+  if ! [[ $MYSQL_DATABASE =~ $IS_STRING ]]; then
+    echo "Failed to configure MYSQL_DATABASE variable. Fallback to default MYSQL_DATABASE value as database"
+    MYSQL_DATABASE="database"
+  else
+    if [[ ${#MYSQL_DATABASE} -gt 32 ]]; then
+      echo "Failed to configure MYSQL_DATABASE variable. Fallback to default MYSQL_DATABASE value as database"
+      MYSQL_DATABASE="database"
+    fi
+  fi
+else
+  echo "Failed to configure MYSQL_DATABASE variable. Fallback to default MYSQL_DATABASE value as database"
+  MYSQL_DATABASE="database"
+fi
+if [[ ! -z $MYSQL_ROOT_PASSWORD ]]; then
+  if ! [[ $MYSQL_ROOT_PASSWORD =~ $IS_PASSWORD ]]; then
+    echo "Failed to configure MYSQL_ROOT_PASSWORD variable. Fallback to default MYSQL_ROOT_PASSWORD value as password"
+    MYSQL_ROOT_PASSWORD="password"
+  fi
+else
+  echo "Failed to configure MYSQL_ROOT_PASSWORD variable. Fallback to default MYSQL_ROOT_PASSWORD value as password"
+  MYSQL_ROOT_PASSWORD="password"
+fi
+# ------------------------------------------------
+# Creating MySQL credentials file
+MYSQL_TEMP_FILE=`mktemp`
+if [ ! -f "$MYSQL_TEMP_FILE" ]; then
+    return 1
+fi
+cat << EOF > $MYSQL_TEMP_FILE
+USE mysql;
+FLUSH PRIVILEGES;
+
+GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;
+GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
+
+UPDATE user SET password=PASSWORD("") WHERE user='root' AND host='localhost';
+
+CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;
+GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USERNAME'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
+
+FLUSH PRIVILEGES;
+EOF
+# ------------------------------------------------
+# Configuring MySQL credentials
+if [ "$(ls -A /data/mysql)" ]; then
+  echo "MySQL already initialized, skipping initialization"
+else
+  echo "MySQL not yet initialized, starting initialization"
+  mysql_install_db > /dev/null
+  mysqld --bootstrap --verbose=0 < $MYSQL_TEMP_FILE
+  rm -f $MYSQL_TEMP_FILE
+fi
+# ------------------------------------------------
+# Cleaning-up configuration variable
+unset MYSQL_USERNAME MYSQL_PASSWORD MYSQL_DATABASE MYSQL_ROOT_PASSWORD
+unset MYSQL_FT_MIN_WORD_LEN MYSQL_FT_MAX_WORD_LEN MYSQL_TABLE_OPEN_CACHE \
+      MYSQL_KEY_BUFFER_SIZE MYSQL_SORT_BUFFER_SIZE MYSQL_READ_BUFFER_SIZE \
+      MYSQL_WRITE_BUFFER_SIZE MYSQL_READ_RND_BUFFER_SIZE MYSQL_MAX_ALLOWED_PACKET \
+      MYSQL_NET_BUFFER_LENGTH MYSQL_MYISAM_SORT_BUFFER_SIZE MYSQL_INNODB_LOG_FILE_SIZE \
+      MYSQL_INNODB_LOG_BUFFER_SIZE MYSQL_INNODB_BUFFER_POOL_SIZE MYSQL_INNODB_USE_NATIVE_AIO      
+unset MYSQL_REPLICATION MYSQL_REPLICATION_SERVER_ID_DEFAULT MYSQL_REPLICATION_SERVER_ID \
+      MYSQL_REPLICATION_MASTER_HOST MYSQL_REPLICATION_MASTER_PORT \
+      MYSQL_REPLICATION_USER MYSQL_REPLICATION_PASSWORD
 
 
 # Execute Everything from Entries
